Tâches Django/Introduction_django/Introduction_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mangalib/', include('mangalib.urls')),
    path('authentification/', include('authentification.urls')),
]

Tâches Django/Introduction_django/authentification/urls.py
from django.urls import path
from . import views

app_name = "authentification"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
]

Tâches Django/Introduction_django/mangalib/urls.py
from django.urls import path
from . import views

app_name = "mangalib"

urlpatterns = [
    path('', views.index, name='index3'),
    path('<int:Livre_id>/', views.show, name='show'),
    path('aouter-livre/', views.add, name='add'),
    path('modifier-livre/<int:Livre_id>/', views.edit, name='edit'),
    path('supprimer-livre/<int:Livre_id>/', views.supp, name='supp'),
]

Tâches Django/Introduction_django/authentification/models.py
from django.db import models

# Create your models here.

Tâches Django/Introduction_django/mangalib/models.py
from django.db import models

class Auteur(models.Model):
  prenom = models.CharField(max_length=100)
  nom = models.CharField(max_length=100)
  date_de_naissance = models.DateField(null=True, blank=True)
  
  def __str__(self):
    return f"{self.prenom} {self.nom}"
  
  class Meta:
    verbose_name = "Auteur"
    verbose_name_plural = "Auteurs"
  
class Livre(models.Model):
  titre = models.CharField(max_length=32, unique=True)
  auteur = models.ForeignKey(Auteur, on_delete=models.CASCADE)
  genre = models.CharField(max_length=50)
  annee_edition = models.PositiveIntegerField()
  prix = models.DecimalField(max_digits=10, decimal_places=2)
  quantite = models.IntegerField(default=1)
  
  def __str__(self):
    return self.titre
  
  class Meta:
    verbose_name = "Livre"
    verbose_name_plural = "Livres"

Tâches Django/Introduction_django/authentification/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

Tâches Django/Introduction_django/mangalib/forms.py
from django import forms
from .models import Auteur, Livre

class LivreForm(forms.ModelForm):
    auteur = forms.ModelChoiceField(queryset= Auteur.objects.all(), label= "Auteur")

    class Meta:
        model = Livre
        fields = ['titre', 'auteur', 'genre', 'annee_edition', 'prix', 'quantite']
        labels = {
            'titre': 'Titre',
            'genre': 'Genre',
            'annee_edition': "Annee d'edition",
            'prix': 'Prix',
            'quantite': 'Quantité' 
        }

Tâches Django/Introduction_django/authentification/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomUserCreationForm

# ----------- Inscription --------------
def register_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Inscription réussie. Vous pouvez maintenant vous connecter.")
            return redirect('authentification:login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
            messages.error(
                request, "Erreur lors de l'inscription. Veuillez vérifier les informations fournies.")
    else:
        form = CustomUserCreationForm()

    return render(request, 'authentification/register.html', {'form': form})
# ---------- Connexion ------------
def login_user(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("mangalib:index3")
        else:
            messages.info(
                request, "Informations d'identifications incorrectes")

    form = AuthenticationForm()
    return render(request, "authentification/login.html", {"form": form})
# ---------- Déconnexion -----------
def logout_user(request):
    logout(request)

    return redirect("authentification:login")

Tâches Django/Introduction_django/mangalib/views.py
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Auteur, Livre
from .forms import LivreForm

def index(request):
    contexte = {
        "Livres": Livre.objects.all()
    }
    return render(request, 'mangalib/index.html', contexte)

@login_required
def show(request, Livre_id):
        context = {
            "Livre": get_object_or_404(Livre, pk = Livre_id)
        }
        return render(request, "mangalib/show.html", context)

@permission_required('mangalib.ajouter-livre')
def add(request):
    if request.method == "POST":
        form = LivreForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("mangalib:index3")
    else:
        form = LivreForm()
        
    return render(request, "mangalib/Livre-form.html", {"form": form})

@permission_required('mangalib.modifier-livre')
def edit(request, Livre_id):
    livre_instance = Livre.objects.get(pk = Livre_id)

    if request.method == "POST":
        form = LivreForm(request.POST, instance = livre_instance)

        if form.is_valid():
            form.save()
            return redirect("mangalib:index3")
    else:
        form = LivreForm(instance = livre_instance)
        
    return render(request, "mangalib/Livre-form.html", {"form": form})

@permission_required('mangalib.supprimer-livre')
def supp(request, Livre_id ):
    livre_instance = Livre.objects.get(pk = Livre_id)
    livre_instance.delete()
    return redirect("mangalib:index3")

Tâches Django/Introduction_django/authentification/templates/authentification/login.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Connexion</title>
    {% tailwind_css %}
  </head>
  <body class="bg-red-500 flex items-center justify-center min-h-screen">
    <div class="bg-white text-white p-8 rounded-lg shadow-lg max-w-sm w-full">
      {% for message in messages %}
        <p class="text-red-500 text-center mb-4">{{ message }}</p>
      {% endfor %}
      <h1 class="text-2xl text-black font-bold text-center mb-6">Connexion</h1>
      <form method="post" class="space-y-4">
        {% csrf_token %}
        <div>
          <label for="username" class="block text-sm font-medium text-red-700"
            >Nom d'utilisateur</label
          >
          <input
            type="text"
            name="username"
            id="username"
            placeholder="Entrer le nom d'utilisateur"
            class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-red-500 focus:border-red-500"
          />
        </div>
        <div>
          <label for="password" class="block text-sm font-medium text-red-700"
            >Mot de passe</label
          >
          <input
            type="password"
            name="password"
            id="password"
            placeholder="Entrer le mot de passe"
            class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-red-500 focus:border-red-500"
          />
        </div>
        <button
          type="submit"
          class="w-full bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700"
        >
          Se Connecter
        </button>
        <p class="text-center text-sm text-gray-500">
          Vous n'avez pas de compte ? <a href="{% url 'authentification:register' %}" class="text-red-600 hover:underline">Créer un compte</a>
        </p>
      </form>
    </div>
  </body>
</html>

Tâches Django/Introduction_django/authentification/templates/authentification/register.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inscription</title>
    {% tailwind_css %}
  </head>
  <body class="bg-green-500 flex items-center justify-center min-h-screen">
    <div class="bg-white p-8 rounded-lg shadow-lg max-w-sm w-full">
      {% for message in messages %}
        <p class="text-red-500 text-center mb-4">{{ message }}</p>
      {% endfor %}
      <h1 class="text-2xl font-bold text-center mb-6">Inscription</h1>
      <form method="post" class="space-y-4">
        {% csrf_token %}
        <div>
          <label for="username" class="block text-sm font-medium text-gray-700"
            >Nom d'utilisateur</label
          >
          <input
            type="text"
            name="username"
            id="username"
            placeholder="Entrer le nom d'utilisateur"
            class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500"
          />
        </div>
        <div>
          <label for="password1" class="block text-sm font-medium text-gray-700"
            >Mot de passe</label
          >
          <input
            type="password"
            name="password1"
            id="password1"
            placeholder="Entrer le mot de passe"
            class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500"
          />
        </div>
        <div>
          <label for="password2" class="block text-sm font-medium text-gray-700"
            >Confirmer le mot de passe</label
          >
          <input
            type="password"
            name="password2"
            id="password2"
            placeholder="Confirmer le mot de passe"
            class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring-green-500 focus:border-green-500"
          />
        </div>
        <button
          type="submit"
          class="w-full bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700"
        >
          S'inscrire
        </button>
        <p class="text-center text-sm text-gray-500">
          Vous avez déjà un compte ? <a href="{% url 'authentification:login' %}" class="text-green-600 hover:underline">Se connecter</a>
        </p>
      </form>
    </div>
  </body>
</html>

Tâches Django/Introduction_django/mangalib/templates/mangalib/Balises&Filtre1.html
<h1 style="color: green">{{titre2}}</h1>

<p>{{message|truncatewords:10}}</p>
<p>la variable message comporte {{message1|length}} caractères</p>
<p>la variable message en minuscule: {{message1|lower}}</p>
<p>la variable message en majuscule: {{message1|upper}}</p>
<p>Nous somme le : {{D1|date:"d/m/Y"}} à {{ D1|date:"H\hi" }}</p>
<p>Publier il y a : {{D2|timesince:D1}}</p>
<p>Nom d'utilisateur : {{username|default:"inconnue"}}</p>
<p>url : {{link}}</p>
<p>url encodée : {{link|urlencode}}</p>
<p>text urliser : {{text|urlize}}</p>
<p>url tronquer : {{text|urlizetrunc:5}}</p>

<p>
    {% if numberOfNews > 0 %}
        <p>{{numberOfNews}} Actualité{{numberOfNews|pluralize}}</p>
    {% else %}
        <p>Ancune actualité disponible</p>
    {% endif %}
</p>

{% if citations %}
    <h3>Citations : </h3>
    <ul>
        <li>{{ citations|random}}</li>
    </ul>
{% else %}
    <p><B>Citations : </B>Aucune citations disponible ...</p>
{% endif %}

Tâches Django/Introduction_django/mangalib/templates/mangalib/Livre-form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index3</title>
  <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
</head>
<body>
  <center>
    <h1 style="color: red">Ajout/Edition d'un nouveau livre</h1>
  </center>

  <form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Ajouter">
  <p><a href="{% url 'mangalib:index3' %}">↩</a></p>
  </form>
</body>
</html>

Tâches Django/Introduction_django/mangalib/templates/mangalib/formulaire.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulaire django</title>
  {% comment %} <link rel="stylesheet" href="{% static 'reset.css' %}"> {% endcomment %}
  <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
</head>
<body>
  <center><h1 style="color: red">{{titre}}</h1></center>
  <form method="post" style="margin: auto; display: block; width: 300px">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
  </form>
</body>
</html>

Tâches Django/Introduction_django/mangalib/templates/mangalib/index.html
{%  load static %}
{% comment %} {%  load customtags %} {% endcomment %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>MangaLib</title>

    <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
    {% comment %} <script src="{% static 'js/script.js' %}"></script> {% endcomment %}
    <link rel="icon" type="image/png" href="{% static 'img/Python-Django.png' %}">
</head>
<body>
    {% comment %} {% include './Balises&Filtre1.html' %} {% endcomment %}
    {% include './index3.html' %}
    {% comment %} {% include './show.html' %} {% endcomment %}
    {% comment %} {% include '../../templatetags/customtags.py' %}; {% endcomment %}
    {% comment %} {% include './formulaire.html' %} {% endcomment %}
</body>
</html>

Tâches Django/Introduction_django/mangalib/templates/mangalib/index2.html
{% now ' d/m/Y H:i:s' %}
    
    <h1 style="color: red">{{titre}}</h1>
    <p>{{message}}<p/>
    {% comment %}  {% endcomment %}

    {% include './other.html' %}
    {% comment %}  {% endcomment %}

    <p>Render-vous sur  <a href="{% url 'indexOfMnglib' %}">MangaLib</a></p>
    
      {% for user in users %}
        <li>{{ user }}</li>
      {% empty%}
        <p>Aucune utilisateur n'est disponible ...</p>
      {% endfor %}


  {% comment %}
    ceci est un commentaire en djngo ...    
  {% endcomment %}

Tâches Django/Introduction_django/mangalib/templates/mangalib/index3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index3</title>
  <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
</head>
<body>
  {% if user.is_authenticated %}
    <p>
      Connecter en tant que : {{ user.username }}  | 
      <a href="{% url "authentification:logout" %}">Se déconnecter</a>
    </p>
  {% else %}
    <p>
      Vous avez un compte ? <a href="{% url 'authentification:login' %}" class="text-red-600 hover:underline">Se connecter</a> / <a href="{% url 'authentification:register' %}" class="text-red-600 hover:underline">Créer un compte</a>
    </p>
  {% endif %}
  <h1 style="color: red">{{ titre }}</h1>

<legend>Liste des mangas disponibles : </legend>
{% if user.is_authenticated %}
  <p><a href="{% url 'mangalib:add'  %}">Ajouter manga ➕</a></p>
{% endif %} 
<table style="width: 100%; height: auto">
  <tr style="background:red;">
    <th>Nom</th>
    <th>Auteur</th>
    <th>Qts</th>
    {% if user.is_authenticated %}
      <th colspan="2">Actions</th>
    {% endif %}
  </tr>
  {% for livre in Livres %}
    <tr style="background:white;" >
      <td>
        <a href="{% url 'mangalib:show' livre.id %}">{{ livre.titre }}</a>
      </td>
      <td style="color:black;">{{ livre.auteur.prenom }} {{ livre.auteur.nom }}</td>
      <td style="color:black;">{{ livre.quantite }}</td>
      {% if user.is_authenticated %}
        <td><a href="{% url 'mangalib:edit' livre.id %}">🖋</a></td>
        <td><a href="{% url 'mangalib:supp'  livre.id %}">❌</a></td>
      {% endif %}
    </tr>
  {% endfor %}
</table>
</body>
</html>

Tâches Django/Introduction_django/mangalib/templates/mangalib/other.html
<li>
  {% lorem 1 b random %}
</li>

Tâches Django/Introduction_django/mangalib/templates/mangalib/show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Show</title>
  {% comment %} <link rel="stylesheet" href="{% static 'reset.css' %}"> {% endcomment %}
  <link rel="stylesheet" href="{% static 'mangalib/css/main.css' %}">
</head>
<body>
  <center><h1 style="color: red">{{Livre.titre}}</h1></center>
  <p>Auteur : {{ Livre.auteur.prenom }} {{ Livre.auteur.nom }}</p>
  <p>Genre : {{ Livre.genre }}</p>
  <p>Date de publication : {{ Livre.annee_edition }}</p>
  <p>Prix : {{ Livre.prix }}</p>
  <p>Quantité : {{Livre.quentite}}</p>
  <p><a href="{% url 'mangalib:index3' %}">↩</a></p>
</body>
</html>

Tâches Django/Introduction_django/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>